function (setGNU)
  set(COMPILER_TYPE "gnu" CACHE INTERNAL "Compiler brand")
  message("Setting GNU Compiler Flags")
  if( (BUILD_RELEASE) OR (BUILD_PRODUCTION) )
    set(GSI_Fortran_FLAGS " ${FOPT3} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} -D_REAL8_ ${GSDCLOUDOPT} -fopenmp -ffree-line-length-0" CACHE INTERNAL "")
    set(EXTRA_LINKER_FLAGS "-lgomp -lnetcdf -lnetcdff" CACHE INTERNAL "")
    set(GSI_CFLAGS "-I. -DFortranByte=char -DFortranInt=int -DFortranLlong='long long'  ${DEBINFO}  -Dfunder" CACHE INTERNAL "" )
    set(ENKF_Fortran_FLAGS " ${FOPT3} -fconvert=big-endian -ffree-line-length-0 -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} -DGFS -D_REAL8_ -fopenmp" CACHE INTERNAL "")
    set(UTIL_Fortran_FLAGS " ${FOPT3} -fconvert=big-endian -ffree-line-length-0 -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} -DWRF -D_REAL8_ -fopenmp" CACHE INTERNAL "")
    set(UTIL_COM_Fortran_FLAGS " ${FOPT3} -fconvert=big-endian -ffree-line-length-0 -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK}" CACHE INTERNAL "")
    set(BUFR_Fortran_FLAGS " ${FOPT3} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} ${frl8} -D_REAL8_ -fopenmp" CACHE INTERNAL "")
    set(BUFR_Fortran_PP_FLAGS " -P " CACHE INTERNAL "")
    set(BUFR_C_FLAGS " ${FOPT3} ${DEBINFO} -DUNDERSCORE  -DDYNAMIC_ALLOCATION -DNFILES=32 -DMAXCD=250 -DMAXNC=600 -DMXNAF=3" CACHE INTERNAL "" )
    set(BACIO_Fortran_FLAGS " ${FOPT3} -fconvert=big-endian ${FREEFORM} -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK}  -D_REAL8_ -fopenmp" CACHE INTERNAL "")
    set(CRTM_Fortran_FLAGS " ${DEBINFO} -std=f2003 -fdollar-ok ${FOPT3} -fconvert=big-endian ${FREEFORM} -fno-second-underscore ${BYTERECLEN} ${UNROLL} -static ${WARNALL} " CACHE INTERNAL "")
    set(NEMSIO_Fortran_FLAGS " ${FOPT3} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK}  -D_REAL8_ -fopenmp" CACHE INTERNAL "")
    set(SIGIO_Fortran_FLAGS " ${FOPT3} -fconvert=big-endian ${FREEFORM} -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK}  -D_REAL8_ -fopenmp" CACHE INTERNAL "")
    set(SFCIO_Fortran_FLAGS " ${FOPT3} ${FREEFORM} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK}  -D_REAL8_ -fopenmp" CACHE INTERNAL "")
    set(SP_Fortran_FLAGS " ${FOPT3} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} ${frl8} -D_REAL8_ -fopenmp -DLINUX" CACHE INTERNAL "")
    set(SP_Fortran_4_FLAGS " ${FOPT3} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} -fopenmp -DLINUX" CACHE INTERNAL "")
    set(SP_F77_FLAGS " ${FOPT3} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} ${frl8} -D_REAL8_ -fopenmp -DLINUX" CACHE INTERNAL "")
    set(SP_F77_4_FLAGS " ${FOPT3} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} -fopenmp -DLINUX" CACHE INTERNAL "")
    set(W3EMC_Fortran_FLAGS " ${FOPT3} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} ${frl8} -D_REAL8_ -fopenmp" CACHE INTERNAL "")
    set(W3EMC_4_Fortran_FLAGS " ${FOPT3} -fconvert=big-endian ${FIXED_SOURCE} -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK}  " CACHE INTERNAL "")
    set(W3NCO_Fortran_FLAGS " ${FOPT3} -fconvert=big-endian ${FIXED_SOURCE} -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} ${frl8} -D_REAL8_ " CACHE INTERNAL "")
    set(W3NCO_4_Fortran_FLAGS " ${FOPT3} -fconvert=big-endian ${FIXED_SOURCE} -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK}  " CACHE INTERNAL "")
    set(W3NCO_C_FLAGS " -DLINUX ${FOPT3} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK}  -D_REAL8_ -fopenmp" CACHE INTERNAL "")
    set(WRFLIB_Fortran_FLAGS " ${FOPT3} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} -D_REAL8_ -fopenmp -ffree-line-length-0" CACHE INTERNAL "")
    set( NCDIAG_Fortran_FLAGS "-ffree-line-length-none" CACHE INTERNAL "" )
    set( NDATE_Fortran_FLAGS "-fconvert=big-endian -DCOMMCODE -DLINUX -DUPPLITTLEENDIAN ${FOPT3} -Wl,-noinhibit-exec" CACHE INTERNAL "")
    set( COV_CALC_FLAGS "-c ${FOPT3} -fconvert=little-endian -ffast-math ${FREEFORM} -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} -fopenmp" CACHE INTERNAL "")
    set(GSDCLOUD_Fortran_FLAGS "${FOPT3} -fconvert=big-endian" CACHE INTERNAL "")
  else( ) #DEBUG
    set(GSI_Fortran_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} -D_REAL8_ ${GSDCLOUDOPT} -fopenmp -ffree-line-length-0" CACHE INTERNAL "")
    set(EXTRA_LINKER_FLAGS "-lgomp -lnetcdf -lnetcdff" CACHE INTERNAL "")
    set(GSI_CFLAGS "-I. -DFortranByte=char -DFortranInt=int -DFortranLlong='long long'  ${GEOS_Fortran_Vect_FPE_Flags}  -Dfunder" CACHE INTERNAL "" )
    set(ENKF_Fortran_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} -fconvert=big-endian -ffree-line-length-0 -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} -DGFS -D_REAL8_ -fopenmp" CACHE INTERNAL "")
    set(UTIL_Fortran_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} -fconvert=big-endian -ffree-line-length-0 -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} -DWRF -D_REAL8_ -fopenmp" CACHE INTERNAL "")
    set(UTIL_COM_Fortran_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} -fconvert=big-endian -ffree-line-length-0 -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK}" CACHE INTERNAL "")
    set(BUFR_Fortran_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} ${frl8} -D_REAL8_ -fopenmp" CACHE INTERNAL "")
    set(BUFR_Fortran_PP_FLAGS " -P " CACHE INTERNAL "")
    set(BUFR_C_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} ${GEOS_Fortran_Vect_FPE_Flags} -DUNDERSCORE  -DDYNAMIC_ALLOCATION -DNFILES=32 -DMAXCD=250 -DMAXNC=600 -DMXNAF=3" CACHE INTERNAL "" )
    set(BACIO_Fortran_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} -fconvert=big-endian ${FREEFORM} -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK}  -D_REAL8_ -fopenmp" CACHE INTERNAL "")
    set(CRTM_Fortran_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} -std=f2003 -fdollar-ok ${GEOS_Fortran_Vect_FPE_Flags} -fconvert=big-endian ${FREEFORM} -fno-second-underscore ${BYTERECLEN} ${UNROLL} -static ${WARNALL} " CACHE INTERNAL "")
    set(NEMSIO_Fortran_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK}  -D_REAL8_ -fopenmp" CACHE INTERNAL "")
    set(SIGIO_Fortran_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} -fconvert=big-endian ${FREEFORM} -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK}  -D_REAL8_ -fopenmp" CACHE INTERNAL "")
    set(SFCIO_Fortran_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} ${FREEFORM} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK}  -D_REAL8_ -fopenmp" CACHE INTERNAL "")
    set(SP_Fortran_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} ${frl8} -D_REAL8_ -fopenmp -DLINUX" CACHE INTERNAL "")
    set(SP_Fortran_4_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} -fopenmp -DLINUX" CACHE INTERNAL "")
    set(SP_F77_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} ${frl8} -D_REAL8_ -fopenmp -DLINUX" CACHE INTERNAL "")
    set(SP_F77_4_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} -fopenmp -DLINUX" CACHE INTERNAL "")
    set(W3EMC_Fortran_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} ${frl8} -D_REAL8_ -fopenmp" CACHE INTERNAL "")
    set(W3EMC_4_Fortran_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} -fconvert=big-endian ${FIXED_SOURCE} -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK}  " CACHE INTERNAL "")
    set(W3NCO_Fortran_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} -fconvert=big-endian ${FIXED_SOURCE} -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} ${frl8} -D_REAL8_ " CACHE INTERNAL "")
    set(W3NCO_4_Fortran_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} -fconvert=big-endian ${FIXED_SOURCE} -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK}  " CACHE INTERNAL "")
    set(W3NCO_C_FLAGS " -DLINUX ${GEOS_Fortran_Vect_FPE_Flags} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK}  -D_REAL8_ -fopenmp" CACHE INTERNAL "")
    set(WRFLIB_Fortran_FLAGS " ${GEOS_Fortran_Vect_FPE_Flags} -fconvert=big-endian -ffast-math -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO} ${DEBINFO}gdb -static ${WARNALL} ${NO_RANGE_CHECK} -D_REAL8_ -fopenmp -ffree-line-length-0" CACHE INTERNAL "")
    set( NCDIAG_Fortran_FLAGS "-ffree-line-length-none" CACHE INTERNAL "" )
    set( NDATE_Fortran_FLAGS "-fconvert=big-endian -DCOMMCODE -DLINUX -DUPPLITTLEENDIAN ${GEOS_Fortran_Vect_FPE_Flags} -Wl,-noinhibit-exec" CACHE INTERNAL "")
    set( COV_CALC_FLAGS "-c ${FOPT3} -fconvert=little-endian -ffast-math ${FREEFORM} -fno-second-underscore ${BYTERECLEN} ${UNROLL} ${DEBINFO}gdb -static ${WARNALL} -fopenmp" CACHE INTERNAL "")
    set(GSDCLOUD_Fortran_FLAGS "${FOPT3} -fconvert=big-endian" CACHE INTERNAL "")
  endif( (BUILD_RELEASE) OR (BUILD_PRODUCTION) )
endfunction()
  
